name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deployment
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Composer install
        uses: php-actions/composer@v6
        with:
          dev: no
        env:
          APP_ENV: prod
          APP_DEBUG: 0


      - name: Node 19.1.0
        uses: actions/setup-node@v1
        with:
          node-version: 19.1.0

      - name: npm install and npm run build
        run: |
          npm i
          npm run build

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_APP_DEBUG: false
          envkey_APP_ENV: "prod"
          envkey_DATABASE_URL: "mysql://${{DB_USER}}:${{DB_PASSWORD}}@localhost:3306/${{DB_NAME}}"
          envkey_SECRET_KEY: ${{ secrets.SECRET_KEY }}
          file_name: .env
          fail_on_empty: false

      - name: copy files to server
        uses: appleboy/scp-action@master
        with:
          HOST: ${{secrets.SSH_HOST}}
          PORT: ${{secrets.SSH_PORT}}
          USERNAME: ${{secrets.SSH_USER}}
          password: ${{secrets.SSH_PASSWORD}}
          target: ${{secrets.SSH_TARGET}}
          source: "./config/*,./migrations/*, ./public/*, ./src/*, ./vendor/*, ./translations/*, ./.env, ./composer.json"
